# Generated by Django 4.1.13 on 2024-09-19 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reactapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsondata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jsondata',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='jsondata',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='UserSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(blank=True, default='Untitled Schema', max_length=255)),
                ('json_data', djongo.models.fields.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
